spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userservice
    username: jwt-sample
    password: 1qazxsw2
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
